// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apdxtyxwlpupgqnouhff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwZHh0eXh3bHB1cGdxbm91aGZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODgzMDIsImV4cCI6MjA2NDY2NDMwMn0.iZrD3qiOH3dAABVR9m_-7WrG3Khd8g5OJk7gxwOOkfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);